# Generated by Django 4.2 on 2023-04-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_costsmodel_name_alter_costsmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costsmodel',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
